version: '3.9'

services:
  storefront:
    build: 
      context: .
      ports:
        - '80:80'
      depends_on:
        - database
      args:
        - region=us-east-1
    environment:
      - runtime_env=dev
  database:
    image: "mysql"
    env_file:
      - ./mysql/env_vars
    # volumes:
    #   - ./mysql:/docker-entrypoint-initdb.d:ro
    #   - kineteco:/var/lib/mysql

# volumes:
#   kineteco: